---
framework:
  - terraform
quiet: true
soft-fail: true
skip-check:
  - CKV_GCP_61  # Ensure that Cloud Storage bucket is not anonymously or publicly accessible
  - CKV_GCP_62  # Ensure that Cloud Storage bucket is not anonymously or publicly readable
