default: true

MD013:
  line_length: 140
  code_blocks: false
  tables: false
  headings: false

MD041: false

MD026:
  punctuation: ".,;:!"

MD022: false

MD032: false

MD024:
  siblings_only: true

MD031: false

MD033:
  allowed_elements: ["img", "br", "sub", "sup"]

MD010:
  code_blocks: false

MD012:
  maximum: 2