name: "OpenTofu Validate"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  validate:
    name: "Validate"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: "1.9.0"
          tofu_wrapper: false

      - name: OpenTofu Init
        id: init
        run: tofu init -backend=false

      - name: OpenTofu Validate
        id: validate
        run: tofu validate

      - name: OpenTofu Format Check
        id: fmt
        run: tofu fmt -check -recursive
